name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/terraform/*

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  deploy_terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Apply
        run: terraform apply -auto-approve
  
  configure_instance:
    runs-on: ubuntu-latest
    needs: deploy_terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Install Docker playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: install_docker.yaml
          directory: ./infrastructure/ansible/playbooks/
          key: ${{ secrets.ANSIBLE_SSH_KEY }}
          options: |
              --inventory ../hosts
              --extra-vars "@variables.yaml"
